// AUTO-GENERATED FILE. DO NOT EDIT.
import '../extended_pid.dart';
import '../obd_pid.dart';

class BmwPids {
  static final List<ExtendedPid> pids = [
    ExtendedPid(
      profile: VehicleProfile.bmw,
      requestCommand: "22F40C",
      canHeader: "6F1",
      code: "22F40C",
      shortName: "BOOSTACT",
      name: "Actual Boost Pressure",
      unit: "mbar",
      category: PidCategory.turbo,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 3000,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.01).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.bmw,
      requestCommand: "22F40D",
      canHeader: "6F1",
      code: "22F40D",
      shortName: "BOOSTTGT",
      name: "Target Boost Pressure",
      unit: "mbar",
      category: PidCategory.turbo,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 3000,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.01).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.bmw,
      requestCommand: "22F423",
      canHeader: "6F1",
      code: "22F423",
      shortName: "RAILACT",
      name: "Actual Rail Pressure",
      unit: "bar",
      category: PidCategory.engine,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 2500,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.1).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.bmw,
      requestCommand: "22F424",
      canHeader: "6F1",
      code: "22F424",
      shortName: "RAILTGT",
      name: "Target Rail Pressure",
      unit: "bar",
      category: PidCategory.engine,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 2500,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.1).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.bmw,
      requestCommand: "22F45B",
      canHeader: "6F1",
      code: "22F45B",
      shortName: "DPFSOOT",
      name: "Dpf Soot Mass",
      unit: "g",
      category: PidCategory.engine,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 100,
      decoder: (b) => b.length >= 1 ? (b[0]*0.1).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.bmw,
      requestCommand: "22F435",
      canHeader: "6F1",
      code: "22F435",
      shortName: "EGT1",
      name: "Exhaust Gas Temp Before Dpf",
      unit: "°C",
      category: PidCategory.temperature,
      colorValue: 0xFF2196F3,
      minExpected: -40,
      maxExpected: 1000,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.1-40).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.bmw,
      requestCommand: "22051A",
      canHeader: "7E1",
      code: "22051A",
      shortName: "TRANSTEMP",
      name: "Transmission Fluid Temp",
      unit: "°C",
      category: PidCategory.temperature,
      colorValue: 0xFF2196F3,
      minExpected: -40,
      maxExpected: 215,
      decoder: (b) => b.length >= 1 ? (b[0]-40).toDouble() : 0.0,
    ),
  ];
}
