// AUTO-GENERATED FILE. DO NOT EDIT.
import '../extended_pid.dart';
import '../obd_pid.dart';

class VagPids {
  static final List<ExtendedPid> pids = [
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "22202A",
      canHeader: "7E0",
      code: "22202A",
      shortName: "CHARGE",
      name: "Rzeczywiste Ciśnienie Doładowania",
      unit: "kPa",
      category: PidCategory.turbo,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 4000,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.1).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "222029",
      canHeader: "7E0",
      code: "222029",
      shortName: "PUTS",
      name: "Zadane Ciśnienie Doładowania (Target)",
      unit: "kPa",
      category: PidCategory.turbo,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 50,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.1).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "22F423",
      canHeader: "7E0",
      code: "22F423",
      shortName: "FRP",
      name: "Ciśnienie Paliwa (Rail/HPFP)",
      unit: "kPa",
      category: PidCategory.fuel,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 10000,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*10).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "2210C0",
      canHeader: "7E0",
      code: "2210C0",
      shortName: "LMBDA",
      name: "Rzeczywisty AFR (Lambda)",
      unit: "lambda",
      category: PidCategory.fuel,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 10,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*.000977).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "221456",
      canHeader: "7E0",
      code: "221456",
      shortName: "LMBDS",
      name: "Zadany AFR (Target Lambda)",
      unit: "",
      category: PidCategory.fuel,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 10,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.000977).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "22200A",
      canHeader: "7E0",
      code: "22200A",
      shortName: "TCC1",
      name: "Korekta Zapłonu (Stuk) Cyl. 1",
      unit: "deg",
      category: PidCategory.engine,
      colorValue: 0xFF2196F3,
      minExpected: -10,
      maxExpected: 0,
      decoder: (b) => b.length >= 2 ? (((b[0] > 127 ? b[0] - 256 : b[0])*256+b[1])*0.01).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "22200B",
      canHeader: "7E0",
      code: "22200B",
      shortName: "TCC2",
      name: "Korekta Zapłonu (Stuk) Cyl. 2",
      unit: "deg",
      category: PidCategory.engine,
      colorValue: 0xFF2196F3,
      minExpected: -10,
      maxExpected: 0,
      decoder: (b) => b.length >= 2 ? (((b[0] > 127 ? b[0] - 256 : b[0])*256+b[1])*0.01).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "22200C",
      canHeader: "7E0",
      code: "22200C",
      shortName: "TCC3",
      name: "Korekta Zapłonu (Stuk) Cyl. 3",
      unit: "",
      category: PidCategory.engine,
      colorValue: 0xFF2196F3,
      minExpected: -10,
      maxExpected: 0,
      decoder: (b) => b.length >= 2 ? (((b[0] > 127 ? b[0] - 256 : b[0])*256+b[1])*0.01).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "22200D",
      canHeader: "7e0",
      code: "22200D",
      shortName: "TCC4",
      name: "Korekta Zapłonu (Stuk) Cyl. 4",
      unit: "",
      category: PidCategory.engine,
      colorValue: 0xFF2196F3,
      minExpected: -10,
      maxExpected: 0,
      decoder: (b) => b.length >= 2 ? (((b[0] > 127 ? b[0] - 256 : b[0])*256+b[1])*0.01).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "222004",
      canHeader: "7E0",
      code: "222004",
      shortName: "TC1",
      name: "Kąt Wyprzedzenia Zapłonu Cyl. 1",
      unit: "",
      category: PidCategory.engine,
      colorValue: 0xFF2196F3,
      minExpected: -10,
      maxExpected: 40,
      decoder: (b) => b.length >= 2 ? (((b[0] > 127 ? b[0] - 256 : b[0])*256+b[1])*0.01).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "22437C",
      canHeader: "7E0",
      code: "22437C",
      shortName: "TORQUE",
      name: "Aktualny Moment Obrotowy",
      unit: "Nm",
      category: PidCategory.engine,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 500,
      decoder: (b) => b.length >= 2 ? (((b[0]*256)+b[1])*0.1).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "2239A2",
      canHeader: "7E0",
      code: "2239A2",
      shortName: "WGDSA",
      name: "Fizyczna Pozycja Wastegate",
      unit: "",
      category: PidCategory.turbo,
      colorValue: 0xFF2196F3,
      minExpected: 0,
      maxExpected: 100,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.01).toDouble() : 0.0,
    ),
    ExtendedPid(
      profile: VehicleProfile.vag,
      requestCommand: "2239A3",
      canHeader: "7E0",
      code: "2239A3",
      shortName: "WGDS",
      name: "Zadana Pozycja Wastegate (Target)",
      unit: "",
      category: PidCategory.turbo,
      colorValue: 0xFF2196F3,
      minExpected: 9,
      maxExpected: 100,
      decoder: (b) => b.length >= 2 ? ((b[0]*256+b[1])*0.01).toDouble() : 0.0,
    ),
  ];
}
