// WYGENEROWANE z KLineKWP1281Lib (getMeasurementValue) — wzory bloków pomiarowych VAG.
// Bajty pomiaru: [wzór, NW, MW]. Używane przy odczycie bloków (KWP1281 / KWP2000 21 xx).

double _s8(int v) => (v >= 128 ? v - 256 : v).toDouble();
double _s16(int hi, int lo) { final v = (hi << 8) | lo; return (v >= 0x8000 ? v - 0x10000 : v).toDouble(); }

class VagBlockFormula {
  final int id;
  final String name;
  final String unit;
  final double Function(int nw, int mw) eval;
  const VagBlockFormula(this.id, this.name, this.unit, this.eval);

  static VagBlockFormula? byId(int id) => _table[id];

  /// Wylicza wartość pola bloku; null dla nieznanego wzoru (zwracane są wtedy surowe bajty).
  static double? decode(int formula, int nw, int mw) {
    final f = _table[formula];
    if (f == null) return null;
    final v = f.eval(nw, mw);
    return v.isFinite ? v : null;
  }

  static final Map<int, VagBlockFormula> _table = {
    0x01: VagBlockFormula(0x01, "RPM", "/min", (nw, mw) => (mw * nw * 0.2).toDouble()),
    0x02: VagBlockFormula(0x02, "Load", "%", (nw, mw) => (mw * nw * 0.002).toDouble()),
    0x03: VagBlockFormula(0x03, "Throttle angle", "°", (nw, mw) => (mw * nw * 0.002).toDouble()),
    0x04: VagBlockFormula(0x04, "Ignition angle", "°", (nw, mw) => ((mw - 127) * nw * -0.01).toDouble()),
    0x05: VagBlockFormula(0x05, "Temperature", "°C", (nw, mw) => ((mw - 100) * nw * 0.1).toDouble()),
    0x06: VagBlockFormula(0x06, "Voltage", "V", (nw, mw) => (mw * nw * 0.001).toDouble()),
    0x07: VagBlockFormula(0x07, "Speed", "km/h", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0x08: VagBlockFormula(0x08, "N/A", "N/A", (nw, mw) => (mw * nw * 0.1).toDouble()),
    0x09: VagBlockFormula(0x09, "Steering angle", "°", (nw, mw) => ((mw - 127) * nw * 0.02).toDouble()),
    0x0A: VagBlockFormula(0x0A, "Text", "Warm/Cold", (nw, mw) => ((mw != 0 ? 1.0 : 0.0)).toDouble()),
    0x0B: VagBlockFormula(0x0B, "Lambda factor", "N/A", (nw, mw) => (1 + ((mw - 128) * nw * 0.0001)).toDouble()),
    0x0C: VagBlockFormula(0x0C, "Resistance", "Ohm", (nw, mw) => (mw * nw * 0.001).toDouble()),
    0x0D: VagBlockFormula(0x0D, "Distance", "mm", (nw, mw) => ((mw - 127) * nw * 0.001).toDouble()),
    0x0E: VagBlockFormula(0x0E, "Pressure", "bar", (nw, mw) => (mw * nw * 0.005).toDouble()),
    0x0F: VagBlockFormula(0x0F, "Injection time", "ms", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0x10: VagBlockFormula(0x10, "Switch positions", "bin(MWb&NWb)", (nw, mw) => (mw & nw).toDouble()),
    0x11: VagBlockFormula(0x11, "2 ASCII letters", "char(NWb)char(MWb)", (nw, mw) => ((nw * 256 + mw)).toDouble()),
    0x12: VagBlockFormula(0x12, "Absolute pressure", "mbar", (nw, mw) => (mw * nw * 0.04).toDouble()),
    0x13: VagBlockFormula(0x13, "Fuel level", "l", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0x14: VagBlockFormula(0x14, "Lambda integrator", "%", (nw, mw) => ((mw - 128) * nw * 1 / 128).toDouble()),
    0x15: VagBlockFormula(0x15, "Voltage", "V", (nw, mw) => (mw * nw * 0.001).toDouble()),
    0x16: VagBlockFormula(0x16, "Injection time", "ms", (nw, mw) => (mw * nw * 0.001).toDouble()),
    0x17: VagBlockFormula(0x17, "Duty cycle", "%", (nw, mw) => (mw * nw * 1 / 256).toDouble()),
    0x18: VagBlockFormula(0x18, "Current", "A", (nw, mw) => (mw * nw * 0.001).toDouble()),
    0x19: VagBlockFormula(0x19, "Mass flow", "g/s", (nw, mw) => ((256 * mw + nw) * 1 / 180).toDouble()),
    0x1A: VagBlockFormula(0x1A, "Temperature", "°C", (nw, mw) => (mw - nw).toDouble()),
    0x1B: VagBlockFormula(0x1B, "Ignition angle", "°", (nw, mw) => ((mw - 128) * nw * 0.01).toDouble()),
    0x1C: VagBlockFormula(0x1C, "N/A", "N/A", (nw, mw) => (mw - nw).toDouble()),
    0x1D: VagBlockFormula(0x1D, "Map number", "Map1/Map2", (nw, mw) => (((mw < nw) ? 1.0 : 2.0)).toDouble()),
    0x1E: VagBlockFormula(0x1E, "Knock correction depth", "°", (nw, mw) => (mw * nw * 1 / 12).toDouble()),
    0x1F: VagBlockFormula(0x1F, "N/A", "N/A", (nw, mw) => (mw * nw * 1 / 2560).toDouble()),
    0x20: VagBlockFormula(0x20, "N/A", "N/A", (nw, mw) => (_s8(mw)).toDouble()),
    0x21: VagBlockFormula(0x21, "Load", "%", (nw, mw) => ((mw / nw) * 100).toDouble()),
    0x22: VagBlockFormula(0x22, "Idle correction", "KW", (nw, mw) => ((mw - 128) * nw * 0.01).toDouble()),
    0x23: VagBlockFormula(0x23, "Fuel rate", "l/h", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0x24: VagBlockFormula(0x24, "Mileage", "km", (nw, mw) => ((nw * 256 + mw) * 10).toDouble()),
    0x25: VagBlockFormula(0x25, "Text from table", "text", (nw, mw) => ((nw * 256 + mw)).toDouble()),
    0x26: VagBlockFormula(0x26, "Segment correction", "KW", (nw, mw) => ((mw - 128) * nw * 0.001).toDouble()),
    0x27: VagBlockFormula(0x27, "Injection mass", "mg/h", (nw, mw) => (nw * mw * 1 / 255).toDouble()),
    0x28: VagBlockFormula(0x28, "Current", "A", (nw, mw) => (((nw * 255 + mw) - 4000) * 0.1).toDouble()),
    0x29: VagBlockFormula(0x29, "Charge", "N/A", (nw, mw) => (nw * 255 + mw).toDouble()),
    0x2A: VagBlockFormula(0x2A, "Power", "kW", (nw, mw) => (((nw * 255 + mw) - 4000) * 0.1).toDouble()),
    0x2B: VagBlockFormula(0x2B, "Battery voltage", "V", (nw, mw) => ((nw * 255 + mw) * 0.1).toDouble()),
    0x2C: VagBlockFormula(0x2C, "Time", "hh:mm", (nw, mw) => (mw / 100.0 + nw).toDouble()),
    0x2D: VagBlockFormula(0x2D, "Fuel rate", "l/km", (nw, mw) => (mw * nw * 0.1).toDouble()),
    0x2E: VagBlockFormula(0x2E, "Segment correction", "KW", (nw, mw) => (((nw * 256) + mw - 32768) * 0.00275).toDouble()),
    0x2F: VagBlockFormula(0x2F, "Time correction", "ms", (nw, mw) => ((mw - 128) * nw).toDouble()),
    0x30: VagBlockFormula(0x30, "N/A", "N/A", (nw, mw) => (nw * 255 + mw).toDouble()),
    0x31: VagBlockFormula(0x31, "Air mass per stroke", "mg/h", (nw, mw) => (nw * mw * 0.025).toDouble()),
    0x32: VagBlockFormula(0x32, "Pressure", "mbar", (nw, mw) => ((mw - 128) * 100 / nw).toDouble()),
    0x33: VagBlockFormula(0x33, "Injection mass", "mg/h", (nw, mw) => ((mw - 128) * nw / 255).toDouble()),
    0x34: VagBlockFormula(0x34, "Torque", "Nm", (nw, mw) => ((mw - 50) * nw * 0.02).toDouble()),
    0x35: VagBlockFormula(0x35, "Mass flow", "g/s", (nw, mw) => (((mw - 128) * 256 + nw) / 180).toDouble()),
    0x36: VagBlockFormula(0x36, "Count", "N/A", (nw, mw) => (nw * 256 + mw).toDouble()),
    0x37: VagBlockFormula(0x37, "Time", "s", (nw, mw) => (mw * nw * 0.005).toDouble()),
    0x38: VagBlockFormula(0x38, "Code for WSC16=0", "N/A", (nw, mw) => ((nw << 8) & mw).toDouble()),
    0x39: VagBlockFormula(0x39, "Code for WSC16=1", "N/A", (nw, mw) => (((nw << 8) & mw) + 65536).toDouble()),
    0x3A: VagBlockFormula(0x3A, "Misfires", "/s", (nw, mw) => (_s8(mw) * 1.023).toDouble()),
    0x3B: VagBlockFormula(0x3B, "Segment correction", "N/A", (nw, mw) => ((nw * 256 + mw) * 1 / 32768).toDouble()),
    0x3C: VagBlockFormula(0x3C, "Time resolution", "s", (nw, mw) => ((nw * 256 + mw) * 1 / 100).toDouble()),
    0x3D: VagBlockFormula(0x3D, "Difference", "N/A", (nw, mw) => ((mw - 128) / nw).toDouble()),
    0x3E: VagBlockFormula(0x3E, "Time", "s", (nw, mw) => (mw * nw * 256 / 1000).toDouble()),
    0x40: VagBlockFormula(0x40, "Resistance", "Ohm", (nw, mw) => (mw + nw).toDouble()),
    0x41: VagBlockFormula(0x41, "Distance", "mm", (nw, mw) => ((mw - 127) * nw * 0.01).toDouble()),
    0x42: VagBlockFormula(0x42, "Voltage", "V", (nw, mw) => (mw * nw / 512).toDouble()),
    0x43: VagBlockFormula(0x43, "Steering angle", "°", (nw, mw) => (_s16(nw, mw) * 2.5).toDouble()),
    0x44: VagBlockFormula(0x44, "Turn rate", "°/s", (nw, mw) => (_s16(nw, mw) * 0.1358).toDouble()),
    0x45: VagBlockFormula(0x45, "Pressure", "bar", (nw, mw) => (_s16(nw, mw) * 0.3255).toDouble()),
    0x46: VagBlockFormula(0x46, "Lat. acceleration", "m/s^2", (nw, mw) => (_s16(nw, mw) * 0.192).toDouble()),
    0x47: VagBlockFormula(0x47, "Distance", "cm", (nw, mw) => (mw * nw).toDouble()),
    0x48: VagBlockFormula(0x48, "Voltage", "V", (nw, mw) => ((nw * 255 + mw * (211 - nw)) / 4080).toDouble()),
    0x49: VagBlockFormula(0x49, "Resistance", "Ohm", (nw, mw) => (nw * mw * 0.01).toDouble()),
    0x4A: VagBlockFormula(0x4A, "Time", "months", (nw, mw) => (0.1 * nw * mw).toDouble()),
    0x4B: VagBlockFormula(0x4B, "Fault code", "N/A", (nw, mw) => (nw * 256 + mw).toDouble()),
    0x4C: VagBlockFormula(0x4C, "Resistance", "kOhm", (nw, mw) => (nw * 255 + mw).toDouble()),
    0x4D: VagBlockFormula(0x4D, "Voltage", "V", (nw, mw) => ((255 * nw + mw * 60) / 4080).toDouble()),
    0x4E: VagBlockFormula(0x4E, "Misfires", "/s", (nw, mw) => (_s8(mw) * 1.819).toDouble()),
    0x4F: VagBlockFormula(0x4F, "Channel number", "N/A", (nw, mw) => (mw).toDouble()),
    0x50: VagBlockFormula(0x50, "Resistance", "kOhm", (nw, mw) => ((nw * 256 + mw) / 100).toDouble()),
    0x51: VagBlockFormula(0x51, "Steering angle", "°", (nw, mw) => (_s16(nw, mw) * 0.04375).toDouble()),
    0x52: VagBlockFormula(0x52, "Lat. acceleration", "m/s^2", (nw, mw) => (_s16(nw, mw) * 0.00981).toDouble()),
    0x53: VagBlockFormula(0x53, "Pressure", "bar", (nw, mw) => (_s16(nw, mw) * 0.01).toDouble()),
    0x54: VagBlockFormula(0x54, "Long. acceleration", "m/s^2", (nw, mw) => (_s16(nw, mw) * 0.0973).toDouble()),
    0x55: VagBlockFormula(0x55, "Turn rate", "°/s", (nw, mw) => (_s16(nw, mw) * 0.002865).toDouble()),
    0x56: VagBlockFormula(0x56, "Current", "A", (nw, mw) => (mw * nw * 0.1).toDouble()),
    0x57: VagBlockFormula(0x57, "Turn rate", "°/s", (nw, mw) => (nw * (mw - 128) * 0.1).toDouble()),
    0x58: VagBlockFormula(0x58, "Resistance", "kOhm", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0x59: VagBlockFormula(0x59, "On-time", "h", (nw, mw) => (nw * 256 + mw).toDouble()),
    0x5A: VagBlockFormula(0x5A, "Weight", "kg", (nw, mw) => (nw * mw * 0.1).toDouble()),
    0x5B: VagBlockFormula(0x5B, "Steering angle", "°", (nw, mw) => (nw * (mw - 128) * 0.1).toDouble()),
    0x5C: VagBlockFormula(0x5C, "Mileage", "km", (nw, mw) => (nw * mw).toDouble()),
    0x5D: VagBlockFormula(0x5D, "Torque", "Nm", (nw, mw) => ((mw - 128) * nw * 0.001).toDouble()),
    0x5E: VagBlockFormula(0x5E, "Torque", "Nm", (nw, mw) => (nw * (mw - 128) * 0.1).toDouble()),
    0x60: VagBlockFormula(0x60, "Pressure", "mbar", (nw, mw) => (nw * mw * 0.1).toDouble()),
    0x61: VagBlockFormula(0x61, "Cat-temperature", "°C", (nw, mw) => ((mw - nw) * 5).toDouble()),
    0x62: VagBlockFormula(0x62, "Impulses", "/km", (nw, mw) => (nw * mw * 0.1).toDouble()),
    0x63: VagBlockFormula(0x63, "N/A", "N/A", (nw, mw) => (_s16(nw, mw)).toDouble()),
    0x64: VagBlockFormula(0x64, "Pressure", "bar", (nw, mw) => (nw * mw * 0.1).toDouble()),
    0x65: VagBlockFormula(0x65, "Fuel level factor", "l/mm", (nw, mw) => (mw * nw * 0.001).toDouble()),
    0x66: VagBlockFormula(0x66, "Fuel level", "mm", (nw, mw) => (mw * nw * 0.1).toDouble()),
    0x67: VagBlockFormula(0x67, "Voltage", "V", (nw, mw) => (nw + mw * 0.05).toDouble()),
    0x68: VagBlockFormula(0x68, "Volume", "ml", (nw, mw) => ((mw - 128) * nw * 0.2).toDouble()),
    0x69: VagBlockFormula(0x69, "Distance", "m", (nw, mw) => ((mw - 128) * nw * 0.01).toDouble()),
    0x6A: VagBlockFormula(0x6A, "Speed", "km/h", (nw, mw) => ((mw - 128) * nw * 0.1).toDouble()),
    0x6B: VagBlockFormula(0x6B, "Hex bytes", "hex(NWb)hex(MWb)", (nw, mw) => (_s16(nw, mw)).toDouble()),
    0x6F: VagBlockFormula(0x6F, "Mileage", "km", (nw, mw) => (0x6F0000 | (nw << 8) | mw).toDouble()),
    0x70: VagBlockFormula(0x70, "Angle", "°", (nw, mw) => ((mw - 128) * nw * 0.001).toDouble()),
    0x71: VagBlockFormula(0x71, "N/A", "N/A", (nw, mw) => ((mw - 128) * nw * 0.01).toDouble()),
    0x72: VagBlockFormula(0x72, "Altitude", "m", (nw, mw) => ((mw - 128) * nw).toDouble()),
    0x73: VagBlockFormula(0x73, "Power", "W", (nw, mw) => (_s16(nw, mw)).toDouble()),
    0x74: VagBlockFormula(0x74, "RPM", "/min", (nw, mw) => (_s16(nw, mw)).toDouble()),
    0x75: VagBlockFormula(0x75, "Temperature", "°C", (nw, mw) => ((mw - 64) * nw * 0.01).toDouble()),
    0x77: VagBlockFormula(0x77, "Percentage", "%", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0x78: VagBlockFormula(0x78, "Angle", "°", (nw, mw) => (mw * nw * 1.41).toDouble()),
    0x79: VagBlockFormula(0x79, "N/A", "N/A", (nw, mw) => (((mw * 256) + nw) * 0.5).toDouble()),
    0x7A: VagBlockFormula(0x7A, "N/A", "N/A", (nw, mw) => (((mw * 256) + nw - 32768) * 0.01).toDouble()),
    0x7B: VagBlockFormula(0x7B, "Text from table", "text", (nw, mw) => ((nw * 256 + mw)).toDouble()),
    0x7C: VagBlockFormula(0x7C, "Current", "mA", (nw, mw) => (mw * nw * 0.1).toDouble()),
    0x7D: VagBlockFormula(0x7D, "Attenuation", "dB", (nw, mw) => (nw - mw).toDouble()),
    0x7E: VagBlockFormula(0x7E, "N/A", "N/A", (nw, mw) => (nw * mw * 0.1).toDouble()),
    0x80: VagBlockFormula(0x80, "RPM", "/min", (nw, mw) => (mw * nw).toDouble()),
    0x81: VagBlockFormula(0x81, "Load", "%", (nw, mw) => (mw * nw * 1 / 256).toDouble()),
    0x82: VagBlockFormula(0x82, "Current", "A", (nw, mw) => (mw * nw * 1 / 2560).toDouble()),
    0x83: VagBlockFormula(0x83, "Ignition angle", "°", (nw, mw) => ((mw * nw * 0.5) - 30).toDouble()),
    0x84: VagBlockFormula(0x84, "Throttle angle", "°", (nw, mw) => (mw * nw * 0.5).toDouble()),
    0x85: VagBlockFormula(0x85, "Voltage", "V", (nw, mw) => (mw * nw * 1 / 256).toDouble()),
    0x86: VagBlockFormula(0x86, "Speed", "km/h", (nw, mw) => (mw * nw).toDouble()),
    0x87: VagBlockFormula(0x87, "N/A", "N/A", (nw, mw) => (mw * nw).toDouble()),
    0x88: VagBlockFormula(0x88, "Switch positions", "bin(MWb&nWb)", (nw, mw) => (mw & nw).toDouble()),
    0x89: VagBlockFormula(0x89, "Injection time", "ms", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0x8A: VagBlockFormula(0x8A, "Knock sensor", "V", (nw, mw) => (mw * nw * 0.001).toDouble()),
    0x8E: VagBlockFormula(0x8E, "2 ASCII letters", "char(NWb)char(MWb)", (nw, mw) => ((nw * 256 + mw)).toDouble()),
    0x8F: VagBlockFormula(0x8F, "Ignition angle", "°", (nw, mw) => ((mw - 128) * nw * 0.01).toDouble()),
    0x90: VagBlockFormula(0x90, "Consumption", "l/h", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0x91: VagBlockFormula(0x91, "Consumption", "N/A", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0x92: VagBlockFormula(0x92, "Lambda factor", "N/A", (nw, mw) => (1 + ((mw - 128) * nw * 0.0001)).toDouble()),
    0x94: VagBlockFormula(0x94, "Slip RPM", "N/A", (nw, mw) => ((mw - 128) * nw * 0.25).toDouble()),
    0x95: VagBlockFormula(0x95, "Temperature", "°C", (nw, mw) => ((mw - 100) * nw * 0.1).toDouble()),
    0x96: VagBlockFormula(0x96, "Mass flow", "g/s", (nw, mw) => ((256 * mw + nw) * 1 / 180).toDouble()),
    0x97: VagBlockFormula(0x97, "Idle correction", "KW", (nw, mw) => ((mw - 128) * nw * 0.01).toDouble()),
    0x98: VagBlockFormula(0x98, "Air mass per stroke", "mg/h", (nw, mw) => (nw * mw * 0.025).toDouble()),
    0x99: VagBlockFormula(0x99, "Injection quantity", "mg/h", (nw, mw) => ((mw - 128) * nw / 255).toDouble()),
    0x9A: VagBlockFormula(0x9A, "Angle", "°", (nw, mw) => (mw * nw).toDouble()),
    0x9B: VagBlockFormula(0x9B, "Angle", "°", (nw, mw) => ((nw * mw * 0.01) - 90).toDouble()),
    0x9C: VagBlockFormula(0x9C, "Distance", "cm", (nw, mw) => ((nw * 256 + mw)).toDouble()),
    0x9D: VagBlockFormula(0x9D, "Distance", "cm", (nw, mw) => (_s16(nw, mw)).toDouble()),
    0x9E: VagBlockFormula(0x9E, "Speed", "km/h", (nw, mw) => ((nw * 256 + mw) * 0.01).toDouble()),
    0x9F: VagBlockFormula(0x9F, "Temperature", "°C", (nw, mw) => (((mw - 127) * 256 + nw) * 0.1).toDouble()),
    0xA1: VagBlockFormula(0xA1, "Binary bytes", "bin(NWb)bin(MWb)", (nw, mw) => ((nw * 256 + mw)).toDouble()),
    0xA2: VagBlockFormula(0xA2, "Angle", "°", (nw, mw) => (nw * mw * 0.448).toDouble()),
    0xA3: VagBlockFormula(0xA3, "Time", "hh:mm", (nw, mw) => (mw / 100.0 + nw).toDouble()),
    0xA4: VagBlockFormula(0xA4, "Percentage", "%", (nw, mw) => (((mw <= 100) ? mw : ((mw > 100 && mw <= 200) ? (mw - 100) : mw))).toDouble()),
    0xA5: VagBlockFormula(0xA5, "Current", "mA", (nw, mw) => (((mw * 256) + nw - 32768)).toDouble()),
    0xA6: VagBlockFormula(0xA6, "Turn rate", "°/s", (nw, mw) => (_s16(nw, mw) * 2.5).toDouble()),
    0xA7: VagBlockFormula(0xA7, "Resistance", "mOhm", (nw, mw) => (mw * nw * 0.001).toDouble()),
    0xA8: VagBlockFormula(0xA8, "Percentage", "%", (nw, mw) => ((256 * nw + mw) * 0.01).toDouble()),
    0xA9: VagBlockFormula(0xA9, "Nernst voltage", "mV", (nw, mw) => (mw * nw + 200).toDouble()),
    0xAA: VagBlockFormula(0xAA, "Ammonia", "g", (nw, mw) => (mw * nw * 1 / 2560).toDouble()),
    0xAB: VagBlockFormula(0xAB, "Nitrogen oxide", "g", (nw, mw) => (mw * nw * 1 / 2560).toDouble()),
    0xAC: VagBlockFormula(0xAC, "Nitrogen oxide", "mg/km", (nw, mw) => (mw * nw).toDouble()),
    0xAD: VagBlockFormula(0xAD, "NOx mass flow", "mg/s", (nw, mw) => (mw * nw * 0.1).toDouble()),
    0xAE: VagBlockFormula(0xAE, "Average DEF", "km", (nw, mw) => (mw * nw * 0.01).toDouble()),
    0xAF: VagBlockFormula(0xAF, "DEF pressure", "bar", (nw, mw) => (mw * nw * 0.005).toDouble()),
    0xB0: VagBlockFormula(0xB0, "NOx concentration", "ppm", (nw, mw) => (mw * nw * 0.1).toDouble()),
    0xB1: VagBlockFormula(0xB1, "Torque", "Nm", (nw, mw) => (((nw - 128) * 256 + mw)).toDouble()),
    0xB2: VagBlockFormula(0xB2, "Turn rate", "°/s", (nw, mw) => (((nw - 128) * 256 + mw) * (6 / 51)).toDouble()),
    0xB3: VagBlockFormula(0xB3, "Quantity", "N/A", (nw, mw) => ((nw * 256 + mw) * 10).toDouble()),
    0xB4: VagBlockFormula(0xB4, "Mass flow", "kg/h", (nw, mw) => (mw * nw * 1 / 256).toDouble()),
    0xB5: VagBlockFormula(0xB5, "Mass flow", "mg/s", (nw, mw) => (mw * nw * 0.001).toDouble()),
  };
}
